### ISSUE TITLE
Task: Allow templates to maintain order

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/ctk-webapp#151]
### Description

Currently, the templates have no order; they are simply sorted alphabetically in the frontend. 

### Tasks

- [x] Add a priority column to the templates table.
- [x] Make the webapp sort by the priority column.
- [x] Allow for changes to the priority by an admin.

**Comment by ReinderVosDeWael** [comment]
Resolved by #153
