### ISSUE TITLE
Task: Homogenize the layout of the templates

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/ctk-webapp#152]
### Description

There's several inconsistencies in the template layout that should be resolved across the entire database.

### Tasks

- [ ] Use bulleted sublists.
- [x] Lists should be left aligned (see sharepoint for exact margins)
- [ ] List headings should all be italicized.
- [x] Fix some lists that continue the numbering from a prior list (c.f. sharepoint) 
- [ ] Fix errors in templates
    - [x] First pass done.
