### ISSUE TITLE
Task: Update to Svelte 5

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/ctk-webapp#166]
### Description

With the release of Svelte 5, we should update sooner rather than later to avoid increasing the conversion workload with new features.

### Tasks

- [ ] Update dependencies to Svelte 5.
- [ ] Assess that everything still works as expected.
- [ ] Conversion to runes can be done on a per-PR basis.

**Comment by ReinderVosDeWael** [comment]
See Notion
